version: '3.1'

services:
  downloader:
    build: src/
    restart: always

    volumes:
      - ${DOWNLOADS_DIR:-./downloads}:/downloads
      - ${DATABASE_DIR:-./database}:/database

    environment:
      COOKIE: ${COOKIE}
      AUTHORIZATION: ${AUTHORIZATION}
      INTERVAL: ${INTERVAL:-24}
